name: gemini_chat_app_tutorial
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_gemini: ^2.0.3
  image_picker: ^1.0.7
  dash_chat_2: ^0.0.20
  file_picker: ^4.2.0
  path_provider: ^2.0.2
  http: ^0.13.3
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/login_image.png
